Repository AY2324S1-CS2103T-W11-4/tp, pull requests merged in 2023-11, with the labels that each got.

#124 Fix Bug: Crash after Edit Command
  src/main/java/seedu/address/logic/commands/AddDevToTeamCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/LinkTreeDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TeamListPanel.java
  src/main/resources/view/LinkTreeDisplay.fxml
  src/main/resources/view/TeamStructureDisplay.fxml
Labels: bug

#126 UG Tree Command: update
  docs/UserGuide.md
  docs/images/UG_images/TreeResultExample.png
  docs/images/Ui.png
Labels: documentation

#130 Update UG Draft
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/model/team/UniqueTeamList.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug, documentation

#211 fix errors in add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: bug

#228 Branch testing and documentation
  docs/UserGuide.md
  docs/images/UG_images/AfterDeleteDevFromTeam.png
  docs/images/UG_images/AfterDeleteTeamCommand.png
  docs/images/UG_images/BeforeDeleteDevFromTeam.png
  docs/images/UG_images/BeforeDeleteTeamCommand.png
  docs/images/UG_images/ClearCommand.png
  docs/team/erohsikivar.md
  docs/team/johndoe.md
  src/main/java/seedu/address/logic/commands/DeleteDeveloperFromTeamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteDeveloperFromTeamCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteDeveloperFromTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTeamCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteDeveloperFromTeamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTeamCommandParserTest.java
Labels: bug, documentation

#235 Branch testing and documentation
  docs/UserGuide.md
  docs/images/UG_images/AddCommand.png
  docs/images/UG_images/AddDevToTeamCommand.png
  docs/images/UG_images/AddDevToTeamCommandExample.png
  docs/images/UG_images/AddNewDevToListExample.png
  docs/images/UG_images/AddTeamCommand.png
  docs/images/UG_images/AddTeamCommandExample.png
  docs/images/UG_images/AfterDeleteDevFromTeam.png
  docs/images/UG_images/AfterDeleteTeamCommand.png
  docs/images/UG_images/BeforeDeleteDevFromTeam.png
  docs/images/UG_images/BeforeDeleteTeamCommand.png
  docs/images/UG_images/DeleteCommand.png
  docs/images/UG_images/DeleteDevFromTeam.png
  docs/images/UG_images/DeletePersonFromListExample.png
  docs/images/UG_images/DeleteTeam.png
  docs/images/UG_images/DeleteTeamLeader.png
  docs/images/UG_images/DeletedPersonFromListExample.png
  docs/images/UG_images/EditCommand.png
  docs/images/UG_images/EditTeamLeaderCommand.png
  docs/images/UG_images/EditTeamNameCommand.png
  docs/images/UG_images/Find.png
  docs/images/UG_images/FindCommand.png
  docs/images/UG_images/FindTeamCommnd.png
  docs/images/UG_images/Findteam.png
  docs/images/UG_images/Hi.png
  docs/images/UG_images/ListCommand.png
  docs/images/UG_images/ListCommandExample.png
  docs/images/UG_images/ListTeam.png
  docs/images/UG_images/ListTeamCommandExample.png
  docs/images/UG_images/Understanding GUI.png
  docs/images/UG_images/WelcomeCommand.png
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/WelcomeCommand.java
  src/test/java/seedu/address/logic/commands/WelcomeCommandTest.java
Labels: bug, documentation

#240 Branch testing and documentation
  _markbind/logs/.4a27e4dd4d52b0b210ca13b42ac22c488093fce8-audit.json
  docs/UserGuide.md
Labels: documentation

#242 Branch testing and documentation
  docs/UserGuide.md
  docs/images/UG_images/FindCommand1.png
  docs/images/UG_images/FindCommand2.png
  docs/images/findAlexDavidResult.png
Labels: documentation

#252 Branch testing and documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#274 Branch testing and documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteTeamCommandDiagram.puml
Labels: bug, documentation
